version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: entitle_db
    restart: always
    environment:
      POSTGRES_DB: entitle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: entitle_backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-key-change-in-prod
      - DATABASE_URL=postgres://postgres:password@db:5432/entitle
      - GROQ_API_KEY=AIzaSyAyGCSjt-6gaKghVRa1ORc9zVSKJWAOuVc
      - POLYGON_AMOY_RPC_URL=https://rpc-amoy.polygon.technology
      - WALLET_PRIVATE_KEY=0x6608bb5cdc9e5a7b59326dd7701c209024101df5af6a11139e2096ac816ba2a4
      - ELIGIBILITY_REGISTRY_ADDRESS=0x0000000000000000000000000000000000000000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: entitle_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
