# Generated by Django 4.2.30 on 2026-08-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0001_initial'),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('eligible', 'Eligible'), ('near_miss', 'Near miss'), ('not_eligible', 'Not eligible')], max_length=16)),
                ('matched_rules', models.JSONField(blank=True, default=list)),
                ('missing_rules', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True, default='')),
                ('explanation_language', models.CharField(blank=True, default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='citizens.citizenprofile')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='schemes.scheme')),
            ],
            options={
                'ordering': ['scheme_id'],
                'unique_together': {('citizen', 'scheme')},
            },
        ),
    ]
