# Generated by Django 6.1 on 2026-08-15 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0001_initial'),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('eligible', 'Eligible'), ('near_miss', 'Near Miss'), ('not_eligible', 'Not Eligible')], max_length=30)),
                ('matched_rules', models.JSONField(default=list)),
                ('missing_rules', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_results', to='citizens.citizenprofile')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_results', to='schemes.scheme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
