# Generated by Django 6.1 on 2026-08-15 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eligibility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_hash', models.CharField(db_index=True, max_length=66)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('explorer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('qr_payload', models.TextField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('eligibility_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='eligibility.eligibilityresult')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
