# Generated by Django 4.2.30 on 2026-08-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eligibility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_json', models.JSONField(default=dict)),
                ('eligibility_hash', models.CharField(db_index=True, max_length=66)),
                ('tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('chain_status', models.CharField(choices=[('simulated', 'Simulated (blockchain not configured)'), ('submitted', 'Submitted to Polygon Amoy'), ('failed', 'Submission failed')], default='simulated', max_length=16)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('eligibility_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='eligibility.eligibilityresult')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
