# Generated by Django 4.2.30 on 2026-08-09 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('residence_area', models.CharField(blank=True, choices=[('rural', 'Rural'), ('urban', 'Urban')], max_length=10, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('student', 'Student'), ('artisan', 'Artisan / craftsperson'), ('self_employed', 'Self-employed'), ('small_business', 'Small business owner'), ('salaried', 'Salaried employee'), ('unorganized_worker', 'Unorganised sector worker'), ('daily_wage', 'Daily wage worker'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=32, null=True)),
                ('income', models.PositiveBigIntegerField(blank=True, help_text='Annual family income in ₹', null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], max_length=10, null=True)),
                ('land_owned', models.BooleanField(blank=True, null=True)),
                ('house_owned', models.BooleanField(blank=True, help_text='Owns a pucca house', null=True)),
                ('bank_account', models.BooleanField(blank=True, null=True)),
                ('income_tax_payer', models.BooleanField(blank=True, null=True)),
                ('disability', models.BooleanField(blank=True, null=True)),
                ('has_daughter_under_10', models.BooleanField(blank=True, null=True)),
                ('aadhaar_linked', models.BooleanField(blank=True, help_text='Aadhaar linked to mobile number', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
