# Generated by Django 6.1 on 2026-08-15 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('land_owned', models.BooleanField(blank=True, null=True)),
                ('disability', models.BooleanField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('caste', models.CharField(blank=True, max_length=20, null=True)),
                ('has_bank_account', models.BooleanField(blank=True, null=True)),
                ('girl_child_age', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
