# Generated by Django 4.2.30 on 2026-08-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('aadhaar_card', 'Aadhaar card'), ('land_ownership_document', 'Land ownership document'), ('income_certificate', 'Income certificate'), ('bank_passbook', 'Bank passbook'), ('ration_card', 'Ration card'), ('birth_certificate', 'Birth certificate')], max_length=40)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('extracted_fields', models.JSONField(blank=True, default=dict)),
                ('is_blurry', models.BooleanField(default=False)),
                ('blur_score', models.FloatField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='citizens.citizenprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
