# Generated by Django 6.1 on 2026-08-15 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('extracted_fields', models.JSONField(default=dict)),
                ('is_blurry', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='citizens.citizenprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
